### ISSUE TITLE
Implement cost of trip

### ISSUE THREAD

**Issue by thisisian** [thisisian/foundations_final#8]
Ideas on how to implement the cost of the trip stretch goal:

Modify node structure to hold the distance to the previous node. 
Have getpath sum the distance as it traverses the tree.

**Comment by lynnaeg** [comment]
Vancouver,North Portland,5.0
North Portland,Hwy 26,9.9
Hwy 26,South Portland,1.0
South Portland,Tigard,8.5
Tigard,Lake Oswego,1.1
Lake Oswego,Tualatin,5.0
Tualatin,Stafford,2.0
Stafford,Wilsonville,4.0
Wilsonville,Aurora,5.0
Aurora,Hubbard,4.4
Hubbard,Woodburn,3.4
Sandy,Boring,7.0
Boring,Gresham,8.5
Gresham,East Portland,15.0
East Portland,i5,1.2
i5,West Portland,3.2
West Portland,Sylvan,1.9
Sylvan,Beaverton, 3.9
Beaverton,Tanasbourne,5.9
Tanasbourne,Hillsboro,6.1
Hillsboro,North Plains,2.5
North Plains,Mountaindale,3.3

**Comment by loganballard** [comment]
I create a semi-solution to this, but it isn't perfect yet.  It isn't even _super_ close.  If we have to use the exact format of the file above, I'm going to have to rethink it.  The way that I currently have it implemented (check out my branch for the actual implementation), is by doing a few things:

**Structural Changes**
1. Node now has two cost members: cost to fwd city, cost to previous city. Both are of type float
2. Node also has a "boolean" field to choose which one of these to use after path has been determined (I'm not wild about this solution but haven't thought of a better one)

**Data File Changes**
1. Change the format of the data file to have the distances in it, where we will have redundant data storage (also not wild about this, but it makes processing simpler)
1. a) the format went from "Exit1,Exit2,...,END" to "distancePrev^City1^distanceFwd,...0.0^END^0.0"

**Logical Changes**
1. When reading in each node the string is parsed into two distances and a city name, and then those values are stored into the node struct (util.c -> getentry())
2. When finding the path to each city, based on which direction the stack is being populated in, the "push" is now accompanied with changing the "boolean" value of the node as an indicator for which of the two costs it stores it will use when printing/adding up the total cost of the path
2. a) NOTE: I haven't yet gotten this to work for distance from junction -> city or city -> junction
3. Currently, when printing the path, the node will now have a flag of which cost is relevant and can be printed, with the last cost being ignored (we will have _n_ cities and _n-1_ costs)

**Comment by lynnaeg** [comment]
I don't think it's necessary to have a previous and forward data node for distances, I want to try just using one data point for distance per node, assuming the junction doesn't have data: Here's a rough diagram:

 ((root (data = NULL))
|
A (Node to A distance)
|
B (A to B distance)
|
C (B to C distance)

When you traverse the graph, you only consume distances you've covered. Since the root node doesn't have any data, you don't end up consuming extra distances, as long as you don't consume the data in the ending node if you're traveling towards the node, and consume the data if you're traveling away from the node. 

Not sure if this will be more or less of a pain than your solution Logan, gonna see how far I can get.

**Comment by loganballard** [comment]
The issue that I found with that would be that traveling in a different direction than forward means that you'll have to grab the distance associated with the second node rather than the node you're currently processing.  Which is not necessarily impossible, I suppose you'll just have to maintain a pointer that is aware of directionality and knows which node it should grab the distance from.

**Comment by lynnaeg** [comment]
Yeah, running into that. I'll jump over to your branch and take a look.

**Comment by lynnaeg** [comment]
Logan and I have this partially implemented, should be finished later today

**Comment by lynnaeg** [comment]
stretch goal completed in getpath() function
